/*
Copyright 2022 DigitalOcean

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

export default {
    simpleApproach: 'Our simple approach to bandwidth',
    poolTitle: 'Bandwidth pool',
    poolDesc: 'Bandwidth allowance generated by your Droplets is accrued at the account level. This means that the bandwidth allocation from each Droplet you add is shared between all the Droplets on your DigitalOcean account.',
    overageTitle: 'Overage charges',
    overageDesc: 'Our bandwidth overage charges are simple to understand and consistent. Each extra GB of bandwidth consumed by a Droplet on your account will be billed at $0.01. As such, an overage of 100 GB would cost you only $1 in overage charges on DigitalOcean.',
};
