module.exports = {
    simpleApproach: 'Our simple approach to bandwidth',
    poolTitle: 'Bandwidth pool',
    poolDesc: 'Bandwidth allowance generated by your Droplets and Kubernetes pool nodes is accrued at the account level. This means that the bandwidth allocation from each Droplet or node you add is shared between all the Droplets and Kubernetes nodes on your DigitalOcean account.',
    overageTitle: 'Overage charges',
    overageDesc: 'Our bandwidth overage charges are simple to understand and consistent. Each extra GB of bandwidth consumed by a Droplet or Kubernetes node on your account will be billed at $0.01. As such, an overage of 100 GB would cost you only $1 in overage charges on DigitalOcean.',
};
